---
abstract: 'config loader like Catalyst::Plugin::ConfigLoader'
author:
  - 'hirafoo <hirafoo@cpan.org>'
build_requires:
  ExtUtils::MakeMaker: 6.42
  Test::Exception: 0
  Test::Synopsis: 0
  YAML::Syck: 0
configure_requires:
  ExtUtils::MakeMaker: 6.42
distribution_type: module
generated_by: 'Module::Install version 0.87'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Config-Divide
no_index:
  directory:
    - inc
    - t
requires:
  Config::Any: 0
  Config::General: 0
  Config::Tiny: 0
  File::Spec: 0
  XML::Simple: 0
  YAML: 0
resources:
  license: http://dev.perl.org/licenses/
  repository: http://github.com/hirafoo/Config-Divide/tree/master
version: 0.03
