main1_only_scalar: i
main1_only_hash:
  i1: i2
  i3: i4
main1_overwritten_by_sub1_hash:
  o1: o2
  o3: o4
main1_overwritten_by_sub1_scalar: o1
main2_only_hash:
  i1: i2
  i3: i4
main2_only_scalar: i
main2_overwritten_by_sub2_hash:
  o1: o2
  o3: o4
main2_overwritten_by_sub2_scalar: o1
