main1_only_scalar: i
main1_only_hash:
  i1: i2
  i3: i4
main1_overwritten_by_sub1_hash:
  n1: n2
  n3: n4
main1_overwritten_by_sub1_scalar: n1
main2_only_hash:
  i1: i2
  i3: i4
main2_only_scalar: i
main2_overwritten_by_sub2_hash:
  n1: n2
  n3: n4
main2_overwritten_by_sub2_scalar: n1
